# Generated by Django 4.1.4 on 2022-12-12 21:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articles_timestamp_articles_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='publish',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
