# Generated by Django 4.1.4 on 2022-12-17 03:09

from django.db import migrations, models
import recipes.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='quantity_as_floar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='unit',
            field=models.CharField(max_length=500, validators=[recipes.validators.validate_unit]),
        ),
    ]
