# Generated by Django 4.1.4 on 2022-12-17 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipeingredient_quantity_as_floar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='quantity_as_floar',
            new_name='quantity_as_float',
        ),
    ]
